<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Staging\Block\Adminhtml\Update\Preview */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<div class="staging-preview-header" data-role="preview-header">
    <a href="<?= $block->escapeUrl($block->getHomeUrl()) ?>" class="logo">
        <img src="<?= $block->escapeUrl($block->getLogoSrc()) ?>"
             alt="<?= $block->escapeHtmlAttr(__('Magento Admin Panel')) ?>"/>
    </a>

    <div class="staging-preview-options">
        <div class="staging-preview-item-title staging-preview-item-calendar"
             data-role="collapsible-title"
             tabindex="3">
            <div class="title">
                <?= $block->escapeHtml(__('Calendar')) ?>
            </div>
            <div class="subtitle" title="<?= $block->escapeHtmlAttr($block->getCalendarTabCaption()) ?>">
                <?= $block->escapeHtml($block->getCalendarTabCaption()) ?>
            </div>
        </div>
        <div class="staging-preview-item-content-wrapper" data-role="collapsible-content">
            <div class="actions-toolbar">
                <button type="button" class="action-default action-primary" data-role="share-button">
                    <span><?= $block->escapeHtml(__('Share')) ?></span>
                </button>
                <button type="button" class="action-default action-primary" data-role="update-button">
                    <span><?= $block->escapeHtml(__('Preview')) ?></span>
                </button>
                <button
                        type="button"
                        class="action-close"
                        title="<?= $block->escapeHtmlAttr(__('Close')) ?>"
                        data-role="collapsible-content-close">
                    <span><?= $block->escapeHtml(__('Close')) ?></span>
                </button>
            </div>
            <div class="staging-preview-item-content">
                <?= $block->getFormHtml() ?>
                <?= $block->getChildHtml('staging_update_preview_grid') ?>
            </div>
        </div>

        <div class="staging-preview-item-title staging-preview-item-customer"
             data-role="collapsible-title"
             tabindex="5">
            <div class="title"><?= $block->escapeHtml(__('Scope')) ?></div>
            <div class="subtitle" title=""></div>
        </div>
        <div class="staging-preview-item-content-wrapper" data-role="collapsible-content">
            <div class="actions-toolbar">
                <button type="button" class="action-default action-primary" data-role="update-button">
                    <span><?= $block->escapeHtml(__('Preview')) ?></span>
                </button>
                <button
                        type="button"
                        class="action-close"
                        title="<?= $block->escapeHtmlAttr(__('Close')) ?>"
                        data-role="collapsible-content-close">
                    <span><?= $block->escapeHtml(__('Close')) ?></span>
                </button>
            </div>
            <div class="staging-preview-item-content">
                <form action="" class="staging-preview-item-segment">
                    <fieldset class="admin__fieldset" data-bind="scope: 'store-views'">
                        <!-- ko template: getTemplate() --><!-- /ko -->
                    </fieldset>
                </form>
            </div>
        </div>

        <!-- Start Preview Viewport Control -->
        <div class="staging-preview-item-title staging-preview-item-viewport"
             data-role="collapsible-title"
             tabindex="7">
            <div class="title"><?= $block->escapeHtml(__('Viewport')) ?></div>
            <div class="subtitle" title=""></div>
        </div>
        <div class="staging-preview-item-content-wrapper" data-role="collapsible-content">
            <div class="staging-preview-item-content">
                <div class="viewport-button" id="viewport-mobile">
                    <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="mobile-alt" class="svg-inline--fa fa-mobile-alt fa-w-10" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><path fill="#c3bbb1" d="M272 0H48C21.5 0 0 21.5 0 48v416c0 26.5 21.5 48 48 48h224c26.5 0 48-21.5 48-48V48c0-26.5-21.5-48-48-48zM160 480c-17.7 0-32-14.3-32-32s14.3-32 32-32 32 14.3 32 32-14.3 32-32 32zm112-108c0 6.6-5.4 12-12 12H60c-6.6 0-12-5.4-12-12V60c0-6.6 5.4-12 12-12h200c6.6 0 12 5.4 12 12v312z"></path></svg>
                </div>
                <div class="viewport-button" id="viewport-tablet">
                <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="tablet-alt" class="svg-inline--fa fa-tablet-alt fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="#c3bbb1" d="M400 0H48C21.5 0 0 21.5 0 48v416c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48V48c0-26.5-21.5-48-48-48zM224 480c-17.7 0-32-14.3-32-32s14.3-32 32-32 32 14.3 32 32-14.3 32-32 32zm176-108c0 6.6-5.4 12-12 12H60c-6.6 0-12-5.4-12-12V60c0-6.6 5.4-12 12-12h328c6.6 0 12 5.4 12 12v312z"></path></svg>
                </div>
                <div class="viewport-button" id="viewport-desktop">
                <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="desktop" class="svg-inline--fa fa-desktop fa-w-18" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path fill="#c3bbb1" d="M528 0H48C21.5 0 0 21.5 0 48v320c0 26.5 21.5 48 48 48h192l-16 48h-72c-13.3 0-24 10.7-24 24s10.7 24 24 24h272c13.3 0 24-10.7 24-24s-10.7-24-24-24h-72l-16-48h192c26.5 0 48-21.5 48-48V48c0-26.5-21.5-48-48-48zm-16 352H64V64h448v288z"></path></svg>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            var vp_mob = document.getElementById('viewport-mobile')

            vp_mob.onclick = function () {
                document.body.classList.add('viewport-mobile');
                document.body.classList.remove('viewport-tablet');
                document.body.classList.remove('viewport-desktop');
            }

            var vp_tab = document.getElementById('viewport-tablet')

            vp_tab.onclick = function () {
                document.body.classList.remove('viewport-mobile');
                document.body.classList.add('viewport-tablet');
                document.body.classList.remove('viewport-desktop');
            }

            var vp_desk = document.getElementById('viewport-desktop')

            vp_desk.onclick = function () {
                document.body.classList.remove('viewport-mobile');
                document.body.classList.remove('viewport-tablet');
                document.body.classList.add('viewport-desktop');
            }

        </script>
        <!-- End Preview Viewport Control -->

    </div>
</div>
<div data-role="share-modal" id="share-modal">
    <p>Please press CTRL+C for copying URL into buffer to share this Preview.</p>
    <input class="admin__legend" name="url" title="Preview Url" type="text" data-role="share-modal-input">
</div>
<?= /* @noEscape */
$secureRenderer->renderTag(
    'style',
    [],
    '#share-modal { display: none; }',
    true
); ?>
<div class="staging-preview-content" data-role="iframe-container">
    <div class="staging-preview-content-dynamic">
        <iframe data-role="preview-iframe"
                frameborder="0"
                src="<?= $block->escapeUrl($block->getPreviewFrontendUrl()) ?>">
        </iframe>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "preview": {
                        "deps": ["store-views"],
                        "component": "Magento_Staging/js/preview/preview",
                        "sidParam": "sidParam",
                        "storeParam": "<?= /* @noEscape */ $block->getStoreParamName() ?>",
                        "versionParam": "<?= /* @noEscape */ $block->getVersionParamName() ?>",
                        "timestampParam": "__timestamp",
                        "signatureParam": "__signature",
                        "previewUrlParam": "<?= /* @noEscape */ $block->getPreviewUrlParamName() ?>",
                        "previewStoreParam": "<?= /* @noEscape */ $block->getPreviewStoreParamName() ?>",
                        "previewVersionParam": "<?= /* @noEscape */ $block->getPreviewVersionParamName() ?>",
                        "datetimeFormat": "<?= $block->escapeJs($block->getDateTimeFormat()) ?>",
                        "timezoneOffset": "<?= $block->escapeJs($block->getTimezoneOffset()) ?>",
                        "baseUrl": "<?= $block->escapeJs($block->escapeUrl($block->getPreviewBackendUrl())) ?>"
                    },
                    "store-views": {
                        "component": "Magento_Ui/js/form/element/select",
                        "label": "Select StoreView",
                        "template": "ui/form/field",
                        "value": "<?= $block->escapeJs($block->escapeHtml($block->getPreviewStoreCode())) ?>",
                        "options": <?= /* @noEscape */ $block->getStoreSelectorOptions() ?>
                    }
                }
            }
        }
    }
</script>
